// <auto-generated />
using System;
using Cinema.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230504085738_users-new")]
    partial class usersnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa9f94a6-3388-45d9-9101-f1ec24e823ad"),
                            Country = "USA",
                            Description = "Nakon katastrofalne nesreće na nepoznatoj planeti, pilot Mils (Adam Drajver) ubrzo otkriva da je zapravo bio nasukan na planetu Zemlju… pre 65 miliona godina.",
                            Director = "Scott Beck",
                            Distributor = "CON Film",
                            Duration = 93,
                            IsDeleted = false,
                            Name = "65",
                            TrailerUrl = "https://www.youtube.com/watch?v=bHXejJq5vr0&t=2s&ab_channel=SonyPicturesEntertainment",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("4c4c4b8c-df57-4db1-8054-7ce438b04e4f"),
                            Country = "USA",
                            Description = "Nakon što je dominirao bokserskim svetom, Adonis Krid je napredovao u karijeri i porodičnom životu. Kada je prijatelj iz detinjstva i bivši boksersko čudo.",
                            Director = "Michael B. Jordan",
                            Distributor = "Blitz Film Video doo",
                            Duration = 116,
                            IsDeleted = false,
                            Name = "Creed 3",
                            TrailerUrl = "https://www.youtube.com/watch?v=lvuR_Ny882g&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("4004fea8-74d2-4a71-a3c8-f05c36536907"),
                            Country = "Serbia",
                            Description = "Priča je smeštena u četiri dana i prati Vuka, tridesetogodišnjeg povratnika iz zatvora koji, gonjen samoubistvom najboljeg druga, pokušava da spase njegovog mlađeg brata na veče godišnjice samoubistva.",
                            Director = "Luka Mihailović",
                            Distributor = "Art Vista",
                            Duration = 105,
                            IsDeleted = false,
                            Name = "Indigo Kristal",
                            TrailerUrl = "https://www.youtube.com/watch?v=8hULM38r66E&ab_channel=ArtVista",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("3b3e3990-3d6a-4aaf-b0e2-ed3eca4261fd"),
                            Country = "USA",
                            Description = "Mišel i Alen su u vezi. Odlučuju da pozovu svoje roditelje da se konačno sretnu kako bi se upoznali pre braka. Ispostavilo se da se roditelji već dobro poznaju, što dovodi do različitih mišljenja o braku.",
                            Director = "Michael Jacobs",
                            Distributor = "Blitz Film Video doo",
                            Duration = 95,
                            IsDeleted = false,
                            Name = "Maybe I Do",
                            TrailerUrl = "https://www.youtube.com/watch?v=MU9wJyel8VU&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c88c34e4-03e5-490e-a22c-0067fd122f73"),
                            Country = "USA",
                            Description = "Nakon poslednjih ubistava koje je počinio Goustfejs, četvoro preživelih napuštaju Vudsboro i započinju novo poglavlje. U filmu VRISAK 6 Melisa Berera („Sem Karpenter“), Jasmin Savoj Braun („Mindi Miks-Martin“), Mejson Guding („Čed Miks-Martin), Džena Ortega („Tara Karpenter“), Hajden Panetir („Kirbi Rid“) i Kortni Koks („Gejl Veders“) vraćaju se svojim ulogama u ovoj franšizi, zajedno sa Džekom Čempionom, Henrijem Černijem, Lijanom Liberato, Dermotom Malronijem, Devinom Nekodom, Tonijem Revolorijem, Džošom Segarom i Samarom Viving.",
                            Director = "Matt Bettinelli-Olpin",
                            Distributor = "Taramount",
                            Duration = 123,
                            IsDeleted = false,
                            Name = "Scream 6",
                            TrailerUrl = "https://www.youtube.com/watch?v=h74AXqw4Opc&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("7cc6f3c7-a0fc-4440-8658-9fded1dcc9f4"),
                            Country = "USA",
                            Description = "Radnja novog filma odvija se širom sveta i donosi akciju posebne vrste. Džon Vik se suočava sa svojim najsmrtonosnijim protivnicima dosad u nadolazećem četvrtom nastavku serijala.",
                            Director = "Chad Stahelski",
                            Distributor = "Blitz Film Video doo",
                            Duration = 169,
                            IsDeleted = false,
                            Name = "John Wick: Chapter 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=80zGq9ABI7k&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("10c86ef1-7e21-441f-8d62-e3054cff95f5"),
                            Country = "USA",
                            Description = "Šarmantni lopov i grupa nesvakidašnjih avanturista upustili su se u epsku pljačku kako bi vratili izgubljenu relikviju. Međutim, kada se sukobe sa pogrešnim ljudima, stvari kreću po zlu.",
                            Director = "Jonathan Goldstein",
                            Distributor = "Taramount",
                            Duration = 134,
                            IsDeleted = false,
                            Name = "Dungeons & Dragons: Honor Among Thieves",
                            TrailerUrl = "https://www.youtube.com/watch?v=IiMinixSXII&t=11s&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("ec928e1d-ce3a-4d3f-86e8-0d589a8c68c5"),
                            Country = "USA",
                            Description = "Godina je 50. pne. Kineska carica je upravo zatvorena nakon državnog udara koji je podstaknuo Deng Tsin Kin, izdajnički princ. Uz pomoć Finaltesisa, feničanskog trgovca i njenog vernog telohranitelja Mai Vei, jedina ćerka carice, princeza Sas-Ji beži u Galiju da zatraži pomoć od dva hrabra ratnika Asteriksa i Obeliksa, koji su obdareni nadljudskom snagom zahvaljujući svom magičnom napitku. Naša dva nerazdvojna heroja rado prihvataju da pomognu princezi da spase svoju majku i oslobodi svoju zemlju. I tako počinje veliko putovanje i avantura na putu za Kinu. Ali Cezar i njegova moćna vojska, žedni novog osvajanja, takođe idu ka Srednjem kraljevstvu...",
                            Director = "Guillaume Canet",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Asterix & Obelix: L'Empire du Milieu",
                            TrailerUrl = "https://www.youtube.com/watch?v=E1-qmncJ5zw&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("23e263bd-30fa-47f4-bbf0-013657b1c507"),
                            Country = "USA",
                            Description = "Zasnovan na komičnom i pokretačkom bestseleru Njujork Tajmsa, film Čovek zvani Oto govori o Otou Andersonu (Tom Henks), mrzovoljnom udovcu kome radost donosi jedino kritikovanje i osuđivanje svojih ogorčenih komšija.",
                            Director = "Marc Forster",
                            Distributor = "CON Film",
                            Duration = 126,
                            IsDeleted = false,
                            Name = "A Man Called Otto",
                            TrailerUrl = "https://www.youtube.com/watch?v=eFYUX9l-m5I&ab_channel=SonyPicturesEntertainment",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("b4943141-f23c-4b27-8280-7bb6fae9e71b"),
                            Country = "USA",
                            Description = "Oskarovska ekipa filma, predvođena Ben Aflekom i Met Dejmonom, u filmu o jednom od najuticajnijih sportskih brendova svih vremena. Priča o legendarnoj patici koja je oduševila Džordana i \"spasila\" Najk! Film nas vraća u period osamdesetih godina, a Met Dejmon tumači lik Sonija Vakare, zaslužnog za potpisivanje ugovora s tada mladom košarkaškom zvezdom Majkl Džordanom. Ben Aflek je u ulozi suosnivača Najka, legendarnog Fila Najta, Džejson Bejtman  je u ulozi Roba Strasera – njegovog direktora marketinga, dok je Vajola Dejvis u ulozi beskompromisne majke koja zna vrednost neizmernog talenta svog sina i košarkaškog fenomena koji će postati najveća sportska legenda svih vremena. U filmu pratimo Vakarovo nastojanje da stekne poverenje Džordanove porodice, trenera i najbližih saradnika s namerom da uveri tada veoma mladu NBA zvezdu u usponu da potpiše partnerski ugovor. Ugovor koji je Najku osigurao poziciju najvećeg brenda sportske odeće i obuće danas.",
                            Director = "Ben Affleck",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Air",
                            TrailerUrl = "https://www.youtube.com/watch?v=QIo12F3Uk0s&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProjectionTypeId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106"),
                            Name = "2D"
                        },
                        new
                        {
                            Id = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2"),
                            Name = "3D"
                        },
                        new
                        {
                            Id = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6"),
                            Name = "4D"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ef9938-6135-44ea-9577-e21b88052f85"),
                            Number = 1,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("d890fe82-1c10-47e6-a58f-d2cc20a1880a"),
                            Number = 2,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("1b895433-f86e-47a1-b39a-f4743d4dd28d"),
                            Number = 3,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("4e4cb5eb-4a3e-473b-ba43-03cc8d41146a"),
                            Number = 4,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("cee74c84-28f7-40a9-8306-bc584311899a"),
                            Number = 1,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("ba334433-4889-4de7-8c2d-09364a78d850"),
                            Number = 2,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("ac4c8b68-b6d8-4019-bad6-f2f3468b2643"),
                            Number = 3,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("ff760ed3-c6b1-4462-bc35-22654d60b0ca"),
                            Number = 4,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("94aad96c-74e3-4c98-9626-2f8c3dcbbb4a"),
                            Number = 5,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("01449d1b-e1f4-41e8-83c0-542a7c9e33c2"),
                            Number = 6,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("87bf0088-380f-43ef-a0bc-e3979f6dad44"),
                            Number = 7,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("60776fef-6417-44c5-9ac5-036d83d82933"),
                            Number = 8,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("3c0790bd-f60e-4c0d-82b7-2d2995bfeab9"),
                            Number = 9,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("1f43615a-3fca-4a2c-b800-7c1cae161be8"),
                            Number = 10,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("fccb650b-14ba-49e2-9f5b-5f36c52ef1df"),
                            Number = 1,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("15e57a3c-059c-4193-aacd-8e10fd59f38f"),
                            Number = 2,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("3bc17172-b28c-4e6c-908c-7740f5717d52"),
                            Number = 3,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("725399b6-9169-4ed4-9e19-854fa89a9307"),
                            Number = 4,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d484a36c-684c-491a-9dc1-cceefa5fa812"),
                            Number = 5,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("b2019762-2c83-44a2-a8c3-80fce9fc6bd3"),
                            Number = 6,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d2768ac8-935b-4dd8-a3fc-6b83c46ec4a0"),
                            Number = 7,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("6fecc9b6-ef50-4c31-bfc1-1de27cdedc9e"),
                            Number = 8,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("e04e566c-2d87-404f-be14-2bd4d2ebe3a9"),
                            Number = 9,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("c2382137-578c-4f68-836f-509db9c8750c"),
                            Number = 10,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("e13bad23-7388-4fa2-b97d-761cb53614a4"),
                            Number = 11,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("5e442277-fcde-42bb-a8f9-87de46eae8d3"),
                            Number = 12,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("b7692d52-b934-4425-9ff0-7758f6765231"),
                            Number = 13,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("52dd18a0-ddf4-4861-9285-0cdac4fb8fb3"),
                            Number = 14,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("6726afe8-42c8-4e6a-8449-991788d05363"),
                            Number = 15,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("2b5cd9f6-43ba-4952-aa77-9bb15d1b69e6"),
                            Number = 16,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("1ffcd6f1-5583-44d5-a28a-e49e762a9b15"),
                            Number = 17,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8639559c-32c4-4646-9914-24a4cce8d92a"),
                            Number = 18,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8deb73de-eb6e-4316-8153-439aa8568df7"),
                            Number = 19,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("5045bc1d-f7ff-4e3e-8173-d06fb3162b91"),
                            Number = 20,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("680e36a4-2671-45c0-bfe1-48b8cbc0efdc"),
                            Number = 1,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("91dd2eaa-1407-4cb2-9638-3c745f4f4e00"),
                            Number = 2,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("cba60072-258c-4d5e-9ada-46db55705fff"),
                            Number = 3,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("9e764c8d-671b-4625-b1e6-e4bf081b0280"),
                            Number = 4,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("93be46e4-cdbc-4c39-807f-b32cac69c343"),
                            Number = 5,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("c560dd83-8fb5-4583-8ea0-69c814d1a13e"),
                            Number = 6,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("0405dba9-4e06-441d-94de-8a159b59f24b"),
                            Number = 7,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("7c045a30-c0f6-4c22-9f1d-2ebc3694a1a7"),
                            Number = 8,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("9d25e738-8958-4b95-b428-a685b62e2cba"),
                            Number = 9,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("3f4701a6-5863-4e2f-baee-e00f264c8a3a"),
                            Number = 10,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("2471c381-d1f1-4a29-bf46-558deed2c934"),
                            Number = 11,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("7d3fbac3-1f1c-4063-936e-9158693fe042"),
                            Number = 12,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("48d0970e-707f-4992-a9dc-1a987a69d1da"),
                            Number = 13,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("69a602d5-c900-4e0e-8c19-65e6e6224340"),
                            Number = 14,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("3c040723-6d04-487f-9606-c40900346361"),
                            Number = 15,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("01943ad6-8a49-4e3e-bd76-92c9b1741188"),
                            Number = 1,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("173dd83d-f881-4be1-b83c-fa6063cb0c8e"),
                            Number = 2,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("05eca72a-0b78-44fd-9d26-71c9c5675d68"),
                            Number = 3,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("6552b201-8d54-4f06-b126-47ba9e6d1d02"),
                            Number = 4,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("badc8d35-5741-45a7-9855-07e1e834695a"),
                            Number = 5,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("04190d0a-73a1-439c-9e0a-2f2c55702f56"),
                            Number = 6,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("e861f5b7-fa78-4ef7-9181-dc71817dffd1"),
                            Number = 7,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("124a3273-6d2c-4e71-8a56-ce0026c0695e"),
                            Number = 8,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("99af3ab1-2c1a-42d1-b4e6-c30998363320"),
                            Number = 9,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("2bb1b74c-adbb-4fc3-bc64-e3edc89eaf1a"),
                            Number = 10,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("2a01d22c-5005-4f49-bf55-270cb969752c"),
                            Number = 11,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("18226d1d-84b9-45ff-9c8f-62967759056f"),
                            Number = 12,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("faabec05-7d21-415b-8709-28f1e7f339ff"),
                            Number = 13,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("fd51bdaf-6c28-4109-8790-5dd88c4a485a"),
                            Number = 14,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("7ca18c4e-eac7-4456-a81a-1dc2d36757a7"),
                            Number = 15,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("30dd27bd-f1ae-4b17-b6d6-2f0a81fccf7c"),
                            Number = 1,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("7d3cd869-1f03-4a69-8a01-381e769fdea3"),
                            Number = 2,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("db35c1e6-9059-4974-8300-aa2400a29880"),
                            Number = 3,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("f93c7c4c-4bbb-45cd-ba6d-4e4877621da3"),
                            Number = 4,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("c95396eb-5321-4123-bf94-8557ef3abcc3"),
                            Number = 5,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("f7a5ebf4-ffe0-45db-b9c4-89962586b7bc"),
                            Number = 6,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("88ab28f6-a737-40f5-8d3f-71036ad31286"),
                            Number = 7,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("a4bec694-1867-4983-a04f-59d41e93b899"),
                            Number = 8,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("ca20bf6b-3d65-46ff-8c44-f30701b30757"),
                            Number = 9,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("abda2c0e-a32f-4f9e-8d05-9cdb3f81f3d7"),
                            Number = 10,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            Name = "Sala 1"
                        },
                        new
                        {
                            Id = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            Name = "Sala 2"
                        },
                        new
                        {
                            Id = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            Name = "Sala 3"
                        },
                        new
                        {
                            Id = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            Name = "Sala 4"
                        },
                        new
                        {
                            Id = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            Name = "Sala 5"
                        },
                        new
                        {
                            Id = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            Name = "Sala 6"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d6bf867-e024-4223-b2fc-63572cba211b"),
                            Created = new DateTime(2023, 5, 4, 10, 57, 38, 137, DateTimeKind.Local).AddTicks(1368),
                            Email = "david.fejes@gmail.com",
                            FirstName = "David",
                            LastName = "Fejes",
                            Password = "davidfejes",
                            Role = "User",
                            Username = "davidfejes"
                        },
                        new
                        {
                            Id = new Guid("62411419-99f5-4bb3-b934-e1ee5e281b65"),
                            Created = new DateTime(2023, 5, 4, 10, 57, 38, 137, DateTimeKind.Local).AddTicks(1546),
                            Email = "stefan.bulaja@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Bulaja",
                            Password = "stefanbulaja",
                            Role = "User",
                            Username = "stefanbulaja"
                        },
                        new
                        {
                            Id = new Guid("16488b2b-14a8-431b-bf54-56c416a79137"),
                            Created = new DateTime(2023, 5, 4, 10, 57, 38, 137, DateTimeKind.Local).AddTicks(1557),
                            Email = "andija.tasic@gmail.com",
                            FirstName = "Andrija",
                            LastName = "Tasic",
                            Password = "andrijatasic",
                            Role = "User",
                            Username = "andrijatasic"
                        });
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("TheaterId", "ProjectionTypeId");

                    b.HasIndex("ProjectionTypeId");

                    b.ToTable("TheaterProjectionType");

                    b.HasData(
                        new
                        {
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        },
                        new
                        {
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Movies.Movie", "Movie")
                        .WithMany("Projections")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", "ProjectionType")
                        .WithMany("Projections")
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", "Theater")
                        .WithMany("Projections")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("ProjectionType");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.Projection", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", null)
                        .WithMany()
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Navigation("Projections");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
