// <auto-generated />
using System;
using Cinema.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230407123943_create-projections")]
    partial class createprojections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8edf654a-2fb8-47b0-b0a5-117e8e417e1c"),
                            Country = "USA",
                            Description = "Nakon katastrofalne nesreće na nepoznatoj planeti, pilot Mils (Adam Drajver) ubrzo otkriva da je zapravo bio nasukan na planetu Zemlju… pre 65 miliona godina.",
                            Director = "Scott Beck",
                            Distributor = "CON Film",
                            Duration = 93,
                            Name = "65",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c5ddcb71-8077-4eaf-b383-04258379789a"),
                            Country = "USA",
                            Description = "Nakon što je dominirao bokserskim svetom, Adonis Krid je napredovao u karijeri i porodičnom životu. Kada je prijatelj iz detinjstva i bivši boksersko čudo.",
                            Director = "Michael B. Jordan",
                            Distributor = "Blitz Film Video doo",
                            Duration = 116,
                            Name = "Creed 3",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("f257c6e7-3193-4cec-80a7-df618651c6af"),
                            Country = "Serbia",
                            Description = "Priča je smeštena u četiri dana i prati Vuka, tridesetogodišnjeg povratnika iz zatvora koji, gonjen samoubistvom najboljeg druga, pokušava da spase njegovog mlađeg brata na veče godišnjice samoubistva.",
                            Director = "Luka Mihailović",
                            Distributor = "Art Vista",
                            Duration = 105,
                            Name = "Indigo Kristal",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("b80cd5a2-9c37-4af1-9228-ed286559d08d"),
                            Country = "USA",
                            Description = "Mišel i Alen su u vezi. Odlučuju da pozovu svoje roditelje da se konačno sretnu kako bi se upoznali pre braka. Ispostavilo se da se roditelji već dobro poznaju, što dovodi do različitih mišljenja o braku.",
                            Director = "Michael Jacobs",
                            Distributor = "Blitz Film Video doo",
                            Duration = 95,
                            Name = "Maybe I Do",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("325dff8d-9dac-4b91-9d80-dd36f74c6a84"),
                            Country = "USA",
                            Description = "Nakon poslednjih ubistava koje je počinio Goustfejs, četvoro preživelih napuštaju Vudsboro i započinju novo poglavlje. U filmu VRISAK 6 Melisa Berera („Sem Karpenter“), Jasmin Savoj Braun („Mindi Miks-Martin“), Mejson Guding („Čed Miks-Martin), Džena Ortega („Tara Karpenter“), Hajden Panetir („Kirbi Rid“) i Kortni Koks („Gejl Veders“) vraćaju se svojim ulogama u ovoj franšizi, zajedno sa Džekom Čempionom, Henrijem Černijem, Lijanom Liberato, Dermotom Malronijem, Devinom Nekodom, Tonijem Revolorijem, Džošom Segarom i Samarom Viving.",
                            Director = "Matt Bettinelli-Olpin",
                            Distributor = "Taramount",
                            Duration = 123,
                            Name = "Scream 6",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("423ebdca-cde1-4d87-b100-514eaee8feb1"),
                            Country = "USA",
                            Description = "Radnja novog filma odvija se širom sveta i donosi akciju posebne vrste. Džon Vik se suočava sa svojim najsmrtonosnijim protivnicima dosad u nadolazećem četvrtom nastavku serijala.",
                            Director = "Chad Stahelski",
                            Distributor = "Blitz Film Video doo",
                            Duration = 169,
                            Name = "John Wick: Chapter 4",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("cc275437-1263-4182-883e-df27fdf194eb"),
                            Country = "USA",
                            Description = "Šarmantni lopov i grupa nesvakidašnjih avanturista upustili su se u epsku pljačku kako bi vratili izgubljenu relikviju. Međutim, kada se sukobe sa pogrešnim ljudima, stvari kreću po zlu.",
                            Director = "Jonathan Goldstein",
                            Distributor = "Taramount",
                            Duration = 134,
                            Name = "Dungeons & Dragons: Honor Among Thieves",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("804beffa-137f-4c2a-b46f-dc19ce1c581d"),
                            Country = "USA",
                            Description = "Godina je 50. pne. Kineska carica je upravo zatvorena nakon državnog udara koji je podstaknuo Deng Tsin Kin, izdajnički princ. Uz pomoć Finaltesisa, feničanskog trgovca i njenog vernog telohranitelja Mai Vei, jedina ćerka carice, princeza Sas-Ji beži u Galiju da zatraži pomoć od dva hrabra ratnika Asteriksa i Obeliksa, koji su obdareni nadljudskom snagom zahvaljujući svom magičnom napitku. Naša dva nerazdvojna heroja rado prihvataju da pomognu princezi da spase svoju majku i oslobodi svoju zemlju. I tako počinje veliko putovanje i avantura na putu za Kinu. Ali Cezar i njegova moćna vojska, žedni novog osvajanja, takođe idu ka Srednjem kraljevstvu...",
                            Director = "Guillaume Canet",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            Name = "Astérix & Obélix: L'Empire du Milieu",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("6b36eef5-3f2f-403d-b600-ccf16325bf58"),
                            Country = "USA",
                            Description = "Zasnovan na komičnom i pokretačkom bestseleru Njujork Tajmsa, film Čovek zvani Oto govori o Otou Andersonu (Tom Henks), mrzovoljnom udovcu kome radost donosi jedino kritikovanje i osuđivanje svojih ogorčenih komšija.",
                            Director = "Marc Forster",
                            Distributor = "CON Film",
                            Duration = 126,
                            Name = "A Man Called Otto",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("45a71d65-36a1-4f99-b7e8-334a15fa9375"),
                            Country = "France",
                            Description = "Zajedno  sa  svojom suprugom Alisom, Semi živi srećno u siromašnom urbanom naselju među prijateljima i komšijama. Za rođendan svog sina, najbogatiji čovek Francuske otvorio je svoju robnu kuću, nudeći dečaku da izabere šta god poželi.",
                            Director = "James Huth",
                            Distributor = "MegaCom Film",
                            Duration = 112,
                            Name = "Le nouveau jouet",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProjectionTypeId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.ProjectionTypes.ProjectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106"),
                            Name = "2D"
                        },
                        new
                        {
                            Id = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2"),
                            Name = "3D"
                        },
                        new
                        {
                            Id = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6"),
                            Name = "4D"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67349d89-f09a-4731-9487-fb6a0337807f"),
                            Number = 1,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("ebb3b9c1-35f6-4a79-8282-ef7f8acf7bfc"),
                            Number = 2,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("b19fa4b6-dfb6-4bc7-8a65-5b1da491d7c8"),
                            Number = 3,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("a0f5967e-596a-415e-ba91-1822ccaf5315"),
                            Number = 4,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("1797adc5-637c-489c-bdfb-f499aa6a7fca"),
                            Number = 1,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("8f719a95-7175-4cbd-8291-6ee4fdf326bd"),
                            Number = 2,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("ad2e5c62-e5a2-4349-b6d2-a1cbcd2ee0b9"),
                            Number = 3,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("97faf199-5219-4dcd-88fc-b7fdf6901b8c"),
                            Number = 4,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("6936300a-b8a2-4c2d-8575-6e47fb184884"),
                            Number = 5,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("ed172829-4eee-42c3-bde3-6e21eb750ce5"),
                            Number = 6,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("76959c34-b82c-4e6b-8d81-c1751cb8c772"),
                            Number = 7,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("0c94f727-14ef-4a86-a2dc-31d21fb6bc8e"),
                            Number = 8,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("09b07e16-0aba-420f-9ebb-3de2b54e8c8f"),
                            Number = 9,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("b33cfd0e-5e5e-4829-83e5-3cd91ff1300c"),
                            Number = 10,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("d97f30a9-36ef-43d1-99fe-801611694d98"),
                            Number = 1,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("7ed6f40a-4962-4dc6-88ef-615820a1d3ed"),
                            Number = 2,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d9555a55-3d96-48fe-8489-677bf1214989"),
                            Number = 3,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("58be8c8f-20e6-47fa-99f0-b28d9440d0eb"),
                            Number = 4,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("fc8eb13f-78f5-448a-a5a7-a482de039f50"),
                            Number = 5,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("242e0eb3-b0a0-4bb1-9058-6cd9372b7e22"),
                            Number = 6,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("eaba6d7b-c36b-4f0c-b9d6-07ea6b65ff10"),
                            Number = 7,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("92984afa-73ac-40c8-b695-51880559687a"),
                            Number = 8,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8cc6f306-031d-4f54-859f-50d2d8fcdae7"),
                            Number = 9,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("0677aae3-738e-489e-a801-4b1f367a9d20"),
                            Number = 10,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("ff9341cf-02fd-42d7-8cd9-7c472b76e1df"),
                            Number = 11,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("c5b2ceac-ac37-4631-8029-220067885393"),
                            Number = 12,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("054b3d8d-4de0-4b28-8d9f-71ecc25a4153"),
                            Number = 13,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("1e7c5daa-009b-48a3-9dd7-bb07f704040d"),
                            Number = 14,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8537687a-0b7e-43d3-9e30-75b9a60baaaf"),
                            Number = 15,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("819dfda1-c344-4b88-9f4f-562b49b47733"),
                            Number = 16,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8a17a697-0bca-4beb-aae6-f5dd0a5e53ee"),
                            Number = 17,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("4a53bb30-ed26-4587-b963-6b0784c74305"),
                            Number = 18,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("185729af-2951-4923-b61d-808ab046ce95"),
                            Number = 19,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("537d2ab8-c8ed-4234-8b05-6e1e8b5eb32e"),
                            Number = 20,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("b0d3a38e-c9f4-41a0-9b05-0e7183a1dcf5"),
                            Number = 1,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("5290b86d-9b83-4074-b411-432454c2ce18"),
                            Number = 2,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("9d06c29c-1666-4403-acb1-968729d3a7b2"),
                            Number = 3,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("c226e415-a548-4793-bba5-9271e2920f9d"),
                            Number = 4,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("90a49ec3-c92b-4382-b02e-aa57ec9b5515"),
                            Number = 5,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("e25d507a-c66e-47e0-9e5f-c619e1abcaad"),
                            Number = 6,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("0b6bea72-9b6f-4a49-a486-6b6ab5943be3"),
                            Number = 7,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("15217988-a8d5-4107-aea6-b5db6dc41be0"),
                            Number = 8,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("3b1da660-f32c-4b9f-9200-ad5b619ce467"),
                            Number = 9,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("4c497e65-8ec9-4848-99de-c27257d96e21"),
                            Number = 10,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("639f03a7-c3fd-46fa-92e6-e61f5cba0704"),
                            Number = 11,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("69568caf-5f88-42de-b5b5-acb14b6e2c0c"),
                            Number = 12,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("7186d0f6-8021-4849-8c20-0641be60b99c"),
                            Number = 13,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("c00bb135-9928-4911-babc-d9d3c67b4392"),
                            Number = 14,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("578f2765-04a6-4439-9912-0fb19a350656"),
                            Number = 15,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("0204f416-b5cf-4a9e-ad2e-64ceed249990"),
                            Number = 1,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("782a9c02-9205-4f79-830e-50bbc984b1dc"),
                            Number = 2,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("c1a9b824-3e1c-4c31-9b42-cab6b4078ae1"),
                            Number = 3,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("f4b35fd5-ad3a-48d6-8aca-0382ab1f0b10"),
                            Number = 4,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("fd6c11bc-4117-4df9-ae49-7d6df667e2ef"),
                            Number = 5,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("a71aedff-fa25-4f02-b33f-3af80d8b8611"),
                            Number = 6,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("3416479d-7dbb-430f-95de-2664503f6cee"),
                            Number = 7,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("0124fca0-1b49-4392-807c-018622830201"),
                            Number = 8,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("1525f157-724c-4d52-aec2-817ec35831ee"),
                            Number = 9,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("b6d30f6e-4a52-4f50-8e85-e8d92654bae2"),
                            Number = 10,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("0a51c0d1-d5df-4814-a5c0-bf8b85da10e6"),
                            Number = 11,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("0f1f965e-f2e9-4a2e-a390-ee0bd951d2cc"),
                            Number = 12,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("a67d7c9e-a03f-4139-bd55-23891dececd0"),
                            Number = 13,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("f2b0c596-95b2-4a6d-9b97-cdb8e68ac0b3"),
                            Number = 14,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("8f921d34-fbc8-49bf-81ac-20809b975ce9"),
                            Number = 15,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("7808bc56-fc88-4e62-8daf-5d214d433b99"),
                            Number = 1,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("3bf5b2e6-bd9f-4325-8cf9-7828d3184a44"),
                            Number = 2,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("8797d467-1ae2-4aa3-8914-d29bcfdaec1b"),
                            Number = 3,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("d35280bd-c046-42a5-9e9d-d7bfbdf7f35a"),
                            Number = 4,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("9c0582bd-f339-4222-b3ba-1a44106e8719"),
                            Number = 5,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("739e3e0b-9966-4557-975c-a7fcf581e0cc"),
                            Number = 6,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("a7bab58f-2eaf-49a3-8be7-f8f79099fb0b"),
                            Number = 7,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("aa658c67-1be9-4b91-b468-a5f506b7c942"),
                            Number = 8,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("1499356c-272d-4bdc-81de-0b3d4bafdf15"),
                            Number = 9,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("cea67c84-a3e0-4e3d-98df-0abbeaa7599d"),
                            Number = 10,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            Name = "Sala 1"
                        },
                        new
                        {
                            Id = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            Name = "Sala 2"
                        },
                        new
                        {
                            Id = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            Name = "Sala 3"
                        },
                        new
                        {
                            Id = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            Name = "Sala 4"
                        },
                        new
                        {
                            Id = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            Name = "Sala 5"
                        },
                        new
                        {
                            Id = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            Name = "Sala 6"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b412283-325c-4a62-a0d4-1b2881864de9"),
                            Created = new DateTime(2023, 4, 7, 14, 39, 43, 606, DateTimeKind.Local).AddTicks(8320),
                            Email = "david.fejes@gmail.com",
                            FirstName = "David",
                            LastName = "Fejes",
                            Password = "davidfejes",
                            Role = "LoggedUser",
                            Username = "davidfejes"
                        },
                        new
                        {
                            Id = new Guid("add6599d-4a7d-4365-b3bc-5e895fa47f5c"),
                            Created = new DateTime(2023, 4, 7, 14, 39, 43, 606, DateTimeKind.Local).AddTicks(8467),
                            Email = "stefan.bulaja@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Bulaja",
                            Password = "stefanbulaja",
                            Role = "LoggedUser",
                            Username = "stefanbulaja"
                        },
                        new
                        {
                            Id = new Guid("af7db1fc-4aba-48c9-8c6d-76ce92097d7e"),
                            Created = new DateTime(2023, 4, 7, 14, 39, 43, 606, DateTimeKind.Local).AddTicks(8485),
                            Email = "andija.tasic@gmail.com",
                            FirstName = "Andrija",
                            LastName = "Tasic",
                            Password = "andrijatasic",
                            Role = "LoggedUser",
                            Username = "andrijatasic"
                        });
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("TheaterId", "ProjectionTypeId");

                    b.HasIndex("ProjectionTypeId");

                    b.ToTable("TheaterProjectionType");

                    b.HasData(
                        new
                        {
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        },
                        new
                        {
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Movies.Movie", "Movie")
                        .WithMany("Projections")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.ProjectionTypes.ProjectionType", "ProjectionType")
                        .WithMany("Projections")
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", "Theater")
                        .WithMany("Projections")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("ProjectionType");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.Projection", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.ProjectionTypes.ProjectionType", null)
                        .WithMany()
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.ProjectionTypes.ProjectionType", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Navigation("Projections");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
