// <auto-generated />
using System;
using Cinema.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230412120141_updated-projection-properties")]
    partial class updatedprojectionproperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50394dce-9d82-4834-bbe2-6fa02aa41440"),
                            Country = "USA",
                            Description = "Nakon katastrofalne nesreće na nepoznatoj planeti, pilot Mils (Adam Drajver) ubrzo otkriva da je zapravo bio nasukan na planetu Zemlju… pre 65 miliona godina.",
                            Director = "Scott Beck",
                            Distributor = "CON Film",
                            Duration = 93,
                            IsDeleted = false,
                            Name = "65",
                            TrailerUrl = "https://www.youtube.com/watch?v=bHXejJq5vr0&t=2s&ab_channel=SonyPicturesEntertainment",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("f68a0b29-91b2-4884-ba25-81f18a3b7ac6"),
                            Country = "USA",
                            Description = "Nakon što je dominirao bokserskim svetom, Adonis Krid je napredovao u karijeri i porodičnom životu. Kada je prijatelj iz detinjstva i bivši boksersko čudo.",
                            Director = "Michael B. Jordan",
                            Distributor = "Blitz Film Video doo",
                            Duration = 116,
                            IsDeleted = false,
                            Name = "Creed 3",
                            TrailerUrl = "https://www.youtube.com/watch?v=lvuR_Ny882g&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("a7b9853d-63a0-4179-9a72-461169e9bee9"),
                            Country = "Serbia",
                            Description = "Priča je smeštena u četiri dana i prati Vuka, tridesetogodišnjeg povratnika iz zatvora koji, gonjen samoubistvom najboljeg druga, pokušava da spase njegovog mlađeg brata na veče godišnjice samoubistva.",
                            Director = "Luka Mihailović",
                            Distributor = "Art Vista",
                            Duration = 105,
                            IsDeleted = false,
                            Name = "Indigo Kristal",
                            TrailerUrl = "https://www.youtube.com/watch?v=8hULM38r66E&ab_channel=ArtVista",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("c5f7ed44-e040-4ac7-874e-e3de5c33ed08"),
                            Country = "USA",
                            Description = "Mišel i Alen su u vezi. Odlučuju da pozovu svoje roditelje da se konačno sretnu kako bi se upoznali pre braka. Ispostavilo se da se roditelji već dobro poznaju, što dovodi do različitih mišljenja o braku.",
                            Director = "Michael Jacobs",
                            Distributor = "Blitz Film Video doo",
                            Duration = 95,
                            IsDeleted = false,
                            Name = "Maybe I Do",
                            TrailerUrl = "https://www.youtube.com/watch?v=MU9wJyel8VU&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("895e5007-06ee-4126-809c-c38650fdedc0"),
                            Country = "USA",
                            Description = "Nakon poslednjih ubistava koje je počinio Goustfejs, četvoro preživelih napuštaju Vudsboro i započinju novo poglavlje. U filmu VRISAK 6 Melisa Berera („Sem Karpenter“), Jasmin Savoj Braun („Mindi Miks-Martin“), Mejson Guding („Čed Miks-Martin), Džena Ortega („Tara Karpenter“), Hajden Panetir („Kirbi Rid“) i Kortni Koks („Gejl Veders“) vraćaju se svojim ulogama u ovoj franšizi, zajedno sa Džekom Čempionom, Henrijem Černijem, Lijanom Liberato, Dermotom Malronijem, Devinom Nekodom, Tonijem Revolorijem, Džošom Segarom i Samarom Viving.",
                            Director = "Matt Bettinelli-Olpin",
                            Distributor = "Taramount",
                            Duration = 123,
                            IsDeleted = false,
                            Name = "Scream 6",
                            TrailerUrl = "https://www.youtube.com/watch?v=h74AXqw4Opc&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("e5faae3f-06a2-4ea1-9ac2-41a162039100"),
                            Country = "USA",
                            Description = "Radnja novog filma odvija se širom sveta i donosi akciju posebne vrste. Džon Vik se suočava sa svojim najsmrtonosnijim protivnicima dosad u nadolazećem četvrtom nastavku serijala.",
                            Director = "Chad Stahelski",
                            Distributor = "Blitz Film Video doo",
                            Duration = 169,
                            IsDeleted = false,
                            Name = "John Wick: Chapter 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=80zGq9ABI7k&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("857fd540-c94d-4147-8300-a2cf2bd65e7b"),
                            Country = "USA",
                            Description = "Šarmantni lopov i grupa nesvakidašnjih avanturista upustili su se u epsku pljačku kako bi vratili izgubljenu relikviju. Međutim, kada se sukobe sa pogrešnim ljudima, stvari kreću po zlu.",
                            Director = "Jonathan Goldstein",
                            Distributor = "Taramount",
                            Duration = 134,
                            IsDeleted = false,
                            Name = "Dungeons & Dragons: Honor Among Thieves",
                            TrailerUrl = "https://www.youtube.com/watch?v=IiMinixSXII&t=11s&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c515105b-be02-4815-bbaf-cbf46a2ca9c3"),
                            Country = "USA",
                            Description = "Godina je 50. pne. Kineska carica je upravo zatvorena nakon državnog udara koji je podstaknuo Deng Tsin Kin, izdajnički princ. Uz pomoć Finaltesisa, feničanskog trgovca i njenog vernog telohranitelja Mai Vei, jedina ćerka carice, princeza Sas-Ji beži u Galiju da zatraži pomoć od dva hrabra ratnika Asteriksa i Obeliksa, koji su obdareni nadljudskom snagom zahvaljujući svom magičnom napitku. Naša dva nerazdvojna heroja rado prihvataju da pomognu princezi da spase svoju majku i oslobodi svoju zemlju. I tako počinje veliko putovanje i avantura na putu za Kinu. Ali Cezar i njegova moćna vojska, žedni novog osvajanja, takođe idu ka Srednjem kraljevstvu...",
                            Director = "Guillaume Canet",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Astérix & Obélix: L'Empire du Milieu",
                            TrailerUrl = "https://www.youtube.com/watch?v=E1-qmncJ5zw&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("99bdf360-6cb1-4a9a-a2ce-9bd38dc67ffb"),
                            Country = "USA",
                            Description = "Zasnovan na komičnom i pokretačkom bestseleru Njujork Tajmsa, film Čovek zvani Oto govori o Otou Andersonu (Tom Henks), mrzovoljnom udovcu kome radost donosi jedino kritikovanje i osuđivanje svojih ogorčenih komšija.",
                            Director = "Marc Forster",
                            Distributor = "CON Film",
                            Duration = 126,
                            IsDeleted = false,
                            Name = "A Man Called Otto",
                            TrailerUrl = "https://www.youtube.com/watch?v=eFYUX9l-m5I&ab_channel=SonyPicturesEntertainment",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("70b62b1f-58dd-4e54-a7c8-f4a54daaa93d"),
                            Country = "USA",
                            Description = "Oskarovska ekipa filma, predvođena Ben Aflekom i Met Dejmonom, u filmu o jednom od najuticajnijih sportskih brendova svih vremena. Priča o legendarnoj patici koja je oduševila Džordana i \"spasila\" Najk! Film nas vraća u period osamdesetih godina, a Met Dejmon tumači lik Sonija Vakare, zaslužnog za potpisivanje ugovora s tada mladom košarkaškom zvezdom Majkl Džordanom. Ben Aflek je u ulozi suosnivača Najka, legendarnog Fila Najta, Džejson Bejtman  je u ulozi Roba Strasera – njegovog direktora marketinga, dok je Vajola Dejvis u ulozi beskompromisne majke koja zna vrednost neizmernog talenta svog sina i košarkaškog fenomena koji će postati najveća sportska legenda svih vremena. U filmu pratimo Vakarovo nastojanje da stekne poverenje Džordanove porodice, trenera i najbližih saradnika s namerom da uveri tada veoma mladu NBA zvezdu u usponu da potpiše partnerski ugovor. Ugovor koji je Najku osigurao poziciju najvećeg brenda sportske odeće i obuće danas.",
                            Director = "Ben Affleck",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Air",
                            TrailerUrl = "https://www.youtube.com/watch?v=QIo12F3Uk0s&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProjectionTypeId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106"),
                            Name = "2D"
                        },
                        new
                        {
                            Id = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2"),
                            Name = "3D"
                        },
                        new
                        {
                            Id = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6"),
                            Name = "4D"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60728b17-d01c-45ea-a65b-53b0ccab9600"),
                            Number = 1,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("270d9e44-4ba5-4e82-97d4-5500a50640ca"),
                            Number = 2,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("7bd3bd10-01be-49b0-8caf-9ba703282541"),
                            Number = 3,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("352455bb-7038-4b30-807f-9cd6f24e697c"),
                            Number = 4,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("8d65c230-0028-47c7-990d-4e161b157b69"),
                            Number = 1,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("e820f4ed-2a44-4c5d-a8cc-bc104229eb4e"),
                            Number = 2,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("fde55c47-4262-43cd-9cdb-1b5a3640c261"),
                            Number = 3,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("a9032a94-6a77-463d-a019-558029b9acac"),
                            Number = 4,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("d99c5b1c-0d70-4212-b3f9-17e4431a2251"),
                            Number = 5,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("e6aa9925-d1e6-49eb-aa81-51d6559284c9"),
                            Number = 6,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("2f613abc-0b73-427e-bcf6-2483ee5e2db4"),
                            Number = 7,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("e7110e26-1bba-44f9-a382-11b9467f31a0"),
                            Number = 8,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("7766e061-dc2d-4456-8f8c-661fa2d00a1a"),
                            Number = 9,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("fbcea388-6235-48d7-99d4-2bb7497d0645"),
                            Number = 10,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("f250575a-eca4-4363-90ae-54955b3c8d61"),
                            Number = 1,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("2a0c003d-a75d-4fce-ab53-07c5e95cf24a"),
                            Number = 2,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("40fd2b3a-cecf-4d8f-8bee-f38cdda82f5d"),
                            Number = 3,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("c09b24a3-203c-49bc-b026-a13f8ae6ace2"),
                            Number = 4,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("91d66dbb-f6ab-447b-b0bf-d0ed79317cd8"),
                            Number = 5,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("2607e2d0-06fa-415c-af7d-bcbd179a953f"),
                            Number = 6,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("65699d10-112e-4ad9-8731-8fff408c638f"),
                            Number = 7,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("f4386030-553f-453d-984c-abe1c35cefc7"),
                            Number = 8,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("acf8011a-1d6a-42b5-9e8f-5211309fd2b5"),
                            Number = 9,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("74442023-901f-4179-acc5-4cda82351eca"),
                            Number = 10,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("1c87ffa3-6f56-47a7-b2c8-84b8e241613c"),
                            Number = 11,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("e1f105b9-4f41-448a-9387-4add7a51ac1e"),
                            Number = 12,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("ff0a7525-5012-42d5-bb5d-4a7cdafdef2b"),
                            Number = 13,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("14182ddb-29f3-488d-bd2d-59cf5fb13bc4"),
                            Number = 14,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("5a05725d-7f7b-4e46-bd5a-74c73e25c668"),
                            Number = 15,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("980b12c5-5f6a-4e82-8fd7-ed910aebf73d"),
                            Number = 16,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("4409b82a-e6ea-4f7e-95d1-7a0d31929696"),
                            Number = 17,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("2effb899-d239-489e-bbe9-56cda5f25296"),
                            Number = 18,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("7b7385ae-b37b-4fe8-af17-9f568d3f1044"),
                            Number = 19,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("ec70d24e-a608-4c06-9ff0-5fd4c7baa70e"),
                            Number = 20,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("23f72b8e-241b-4b2e-99c1-6fbc071fd7ad"),
                            Number = 1,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("e794772a-b7e2-471d-bc3a-3a20525efe21"),
                            Number = 2,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("9da6859d-59fc-4f67-9101-16ca91ee497a"),
                            Number = 3,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("b7a15d2b-eda6-475c-a44e-501def7989e3"),
                            Number = 4,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("dee35ed4-f5ce-43d9-8a4f-cd5e826c23af"),
                            Number = 5,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("360eb32a-7388-4a67-ba58-038fdbe5c0da"),
                            Number = 6,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("46c4464f-d299-40c7-b428-cf83ba0d6265"),
                            Number = 7,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("a84b416f-f3cc-4d73-a476-ec5d4ba426d3"),
                            Number = 8,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("0e74d50c-8180-4906-9997-308ef50cccc3"),
                            Number = 9,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("49a3ae4d-1642-4fd5-b81c-df350b52eb49"),
                            Number = 10,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("c8e95ffb-74ea-4ea2-8aa6-910738781fb3"),
                            Number = 11,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("f7c1a61e-4426-4c8d-85d3-a3f0115c16b7"),
                            Number = 12,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("19e495c1-5141-42cd-a03b-2eb26e81643b"),
                            Number = 13,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("8dbfeb3a-9d63-46ef-9bcc-7a746fb3a71e"),
                            Number = 14,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("807d3ac9-4c74-47ed-a898-5c0e7359f386"),
                            Number = 15,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("3f8c4d75-0342-4f29-aff8-a9328e52f9cf"),
                            Number = 1,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("eeed9281-171a-49df-bb0a-3850ed7b23d0"),
                            Number = 2,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("20c04730-88a4-4eb9-a68d-33b233b36a60"),
                            Number = 3,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("d825620d-c3cf-42c2-9f8b-6909b5573d3d"),
                            Number = 4,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("b93310d3-8671-49f1-bea9-98d9fa59dc5f"),
                            Number = 5,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("c46b41ea-aaf7-42c6-ac31-aa65e6280a24"),
                            Number = 6,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("a56731ac-ac02-4bac-ae63-bf3974901186"),
                            Number = 7,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("5cefb832-8ad7-4ac8-9bf8-793632ac7818"),
                            Number = 8,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("c99a177d-04bd-498a-8d82-8f659646b405"),
                            Number = 9,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("637e84cb-1733-4675-90f1-3a9e0ce9849a"),
                            Number = 10,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("17f1af7f-24c2-45b4-b497-82fe5efea046"),
                            Number = 11,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("e2f8a674-47cb-46d6-bea0-5dea3f1b2a27"),
                            Number = 12,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("08d36a13-b78d-4dec-bcee-d467fb8942aa"),
                            Number = 13,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("7451455f-79f1-46e7-8b7d-205f57ce354d"),
                            Number = 14,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("5785c8ea-a67b-4386-abaa-7625a93e8062"),
                            Number = 15,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("5ce748d0-798e-4e7c-9221-bf3072aff854"),
                            Number = 1,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("5eab7373-6526-400b-bf30-df820617628b"),
                            Number = 2,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("a8e3fb7f-2153-410d-9966-9849b417da00"),
                            Number = 3,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("a0fd7c63-94d8-47de-b223-7caca6795785"),
                            Number = 4,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("b36f60b5-0ebe-4145-958a-233cc81ece2a"),
                            Number = 5,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("05bdb40f-5afa-4d0c-8e84-8a052c52a846"),
                            Number = 6,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("249c06b1-9061-47a7-85f6-455c915b7624"),
                            Number = 7,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("001bf436-121a-4a24-8331-794070399c61"),
                            Number = 8,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("00d53e1f-d8ca-42f4-a14c-9b0bd34bbd70"),
                            Number = 9,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("5ea85381-04ba-44d6-a345-e0c451198af4"),
                            Number = 10,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            Name = "Sala 1"
                        },
                        new
                        {
                            Id = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            Name = "Sala 2"
                        },
                        new
                        {
                            Id = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            Name = "Sala 3"
                        },
                        new
                        {
                            Id = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            Name = "Sala 4"
                        },
                        new
                        {
                            Id = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            Name = "Sala 5"
                        },
                        new
                        {
                            Id = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            Name = "Sala 6"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36b4b607-cd84-48fd-9836-c6675a7a7893"),
                            Created = new DateTime(2023, 4, 12, 14, 1, 41, 253, DateTimeKind.Local).AddTicks(6195),
                            Email = "david.fejes@gmail.com",
                            FirstName = "David",
                            LastName = "Fejes",
                            Password = "davidfejes",
                            Role = "LoggedUser",
                            Username = "davidfejes"
                        },
                        new
                        {
                            Id = new Guid("4e557e83-e22b-4996-ab58-a7df54102d85"),
                            Created = new DateTime(2023, 4, 12, 14, 1, 41, 253, DateTimeKind.Local).AddTicks(6334),
                            Email = "stefan.bulaja@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Bulaja",
                            Password = "stefanbulaja",
                            Role = "LoggedUser",
                            Username = "stefanbulaja"
                        },
                        new
                        {
                            Id = new Guid("e23bdbf7-77b5-42a8-bba3-43f12e448031"),
                            Created = new DateTime(2023, 4, 12, 14, 1, 41, 253, DateTimeKind.Local).AddTicks(6350),
                            Email = "andija.tasic@gmail.com",
                            FirstName = "Andrija",
                            LastName = "Tasic",
                            Password = "andrijatasic",
                            Role = "LoggedUser",
                            Username = "andrijatasic"
                        });
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("TheaterId", "ProjectionTypeId");

                    b.HasIndex("ProjectionTypeId");

                    b.ToTable("TheaterProjectionType");

                    b.HasData(
                        new
                        {
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        },
                        new
                        {
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Movies.Movie", "Movie")
                        .WithMany("Projections")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", "ProjectionType")
                        .WithMany("Projections")
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", "Theater")
                        .WithMany("Projections")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("ProjectionType");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.Projection", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", null)
                        .WithMany()
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Navigation("Projections");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
