// <auto-generated />
using System;
using Cinema.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230419152441_test-seed1")]
    partial class testseed1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d36f09bc-f9fd-4ddf-a96a-6bbedef444be"),
                            Country = "USA",
                            Description = "Nakon katastrofalne nesreće na nepoznatoj planeti, pilot Mils (Adam Drajver) ubrzo otkriva da je zapravo bio nasukan na planetu Zemlju… pre 65 miliona godina.",
                            Director = "Scott Beck",
                            Distributor = "CON Film",
                            Duration = 93,
                            IsDeleted = false,
                            Name = "65",
                            TrailerUrl = "https://www.youtube.com/watch?v=bHXejJq5vr0&t=2s&ab_channel=SonyPicturesEntertainment",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("fe3ba5a3-9894-424a-a2b6-018a378b8b55"),
                            Country = "USA",
                            Description = "Nakon što je dominirao bokserskim svetom, Adonis Krid je napredovao u karijeri i porodičnom životu. Kada je prijatelj iz detinjstva i bivši boksersko čudo.",
                            Director = "Michael B. Jordan",
                            Distributor = "Blitz Film Video doo",
                            Duration = 116,
                            IsDeleted = false,
                            Name = "Creed 3",
                            TrailerUrl = "https://www.youtube.com/watch?v=lvuR_Ny882g&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("5572f9dd-3186-463c-934b-434a13bf6616"),
                            Country = "Serbia",
                            Description = "Priča je smeštena u četiri dana i prati Vuka, tridesetogodišnjeg povratnika iz zatvora koji, gonjen samoubistvom najboljeg druga, pokušava da spase njegovog mlađeg brata na veče godišnjice samoubistva.",
                            Director = "Luka Mihailović",
                            Distributor = "Art Vista",
                            Duration = 105,
                            IsDeleted = false,
                            Name = "Indigo Kristal",
                            TrailerUrl = "https://www.youtube.com/watch?v=8hULM38r66E&ab_channel=ArtVista",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("54e55e63-69b9-4a3e-a9c1-0979849d7015"),
                            Country = "USA",
                            Description = "Mišel i Alen su u vezi. Odlučuju da pozovu svoje roditelje da se konačno sretnu kako bi se upoznali pre braka. Ispostavilo se da se roditelji već dobro poznaju, što dovodi do različitih mišljenja o braku.",
                            Director = "Michael Jacobs",
                            Distributor = "Blitz Film Video doo",
                            Duration = 95,
                            IsDeleted = false,
                            Name = "Maybe I Do",
                            TrailerUrl = "https://www.youtube.com/watch?v=MU9wJyel8VU&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("dc74c0e3-d525-41b7-86e1-b50a48307c3e"),
                            Country = "USA",
                            Description = "Nakon poslednjih ubistava koje je počinio Goustfejs, četvoro preživelih napuštaju Vudsboro i započinju novo poglavlje. U filmu VRISAK 6 Melisa Berera („Sem Karpenter“), Jasmin Savoj Braun („Mindi Miks-Martin“), Mejson Guding („Čed Miks-Martin), Džena Ortega („Tara Karpenter“), Hajden Panetir („Kirbi Rid“) i Kortni Koks („Gejl Veders“) vraćaju se svojim ulogama u ovoj franšizi, zajedno sa Džekom Čempionom, Henrijem Černijem, Lijanom Liberato, Dermotom Malronijem, Devinom Nekodom, Tonijem Revolorijem, Džošom Segarom i Samarom Viving.",
                            Director = "Matt Bettinelli-Olpin",
                            Distributor = "Taramount",
                            Duration = 123,
                            IsDeleted = false,
                            Name = "Scream 6",
                            TrailerUrl = "https://www.youtube.com/watch?v=h74AXqw4Opc&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("b6a2cf24-1c5a-4178-9ef3-2bf14168026e"),
                            Country = "USA",
                            Description = "Radnja novog filma odvija se širom sveta i donosi akciju posebne vrste. Džon Vik se suočava sa svojim najsmrtonosnijim protivnicima dosad u nadolazećem četvrtom nastavku serijala.",
                            Director = "Chad Stahelski",
                            Distributor = "Blitz Film Video doo",
                            Duration = 169,
                            IsDeleted = false,
                            Name = "John Wick: Chapter 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=80zGq9ABI7k&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("3094e5b9-9014-4ce3-8768-b2dd00bc8952"),
                            Country = "USA",
                            Description = "Šarmantni lopov i grupa nesvakidašnjih avanturista upustili su se u epsku pljačku kako bi vratili izgubljenu relikviju. Međutim, kada se sukobe sa pogrešnim ljudima, stvari kreću po zlu.",
                            Director = "Jonathan Goldstein",
                            Distributor = "Taramount",
                            Duration = 134,
                            IsDeleted = false,
                            Name = "Dungeons & Dragons: Honor Among Thieves",
                            TrailerUrl = "https://www.youtube.com/watch?v=IiMinixSXII&t=11s&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("5f1e082a-9c88-42ef-9db8-d5a2eb56ab23"),
                            Country = "USA",
                            Description = "Godina je 50. pne. Kineska carica je upravo zatvorena nakon državnog udara koji je podstaknuo Deng Tsin Kin, izdajnički princ. Uz pomoć Finaltesisa, feničanskog trgovca i njenog vernog telohranitelja Mai Vei, jedina ćerka carice, princeza Sas-Ji beži u Galiju da zatraži pomoć od dva hrabra ratnika Asteriksa i Obeliksa, koji su obdareni nadljudskom snagom zahvaljujući svom magičnom napitku. Naša dva nerazdvojna heroja rado prihvataju da pomognu princezi da spase svoju majku i oslobodi svoju zemlju. I tako počinje veliko putovanje i avantura na putu za Kinu. Ali Cezar i njegova moćna vojska, žedni novog osvajanja, takođe idu ka Srednjem kraljevstvu...",
                            Director = "Guillaume Canet",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Astérix & Obélix: L'Empire du Milieu",
                            TrailerUrl = "https://www.youtube.com/watch?v=E1-qmncJ5zw&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("9983a371-a0da-40ab-9f05-862afc7bb6fb"),
                            Country = "USA",
                            Description = "Zasnovan na komičnom i pokretačkom bestseleru Njujork Tajmsa, film Čovek zvani Oto govori o Otou Andersonu (Tom Henks), mrzovoljnom udovcu kome radost donosi jedino kritikovanje i osuđivanje svojih ogorčenih komšija.",
                            Director = "Marc Forster",
                            Distributor = "CON Film",
                            Duration = 126,
                            IsDeleted = false,
                            Name = "A Man Called Otto",
                            TrailerUrl = "https://www.youtube.com/watch?v=eFYUX9l-m5I&ab_channel=SonyPicturesEntertainment",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("77fe051a-4e0b-443f-b75c-3cdc20a28e4c"),
                            Country = "USA",
                            Description = "Oskarovska ekipa filma, predvođena Ben Aflekom i Met Dejmonom, u filmu o jednom od najuticajnijih sportskih brendova svih vremena. Priča o legendarnoj patici koja je oduševila Džordana i \"spasila\" Najk! Film nas vraća u period osamdesetih godina, a Met Dejmon tumači lik Sonija Vakare, zaslužnog za potpisivanje ugovora s tada mladom košarkaškom zvezdom Majkl Džordanom. Ben Aflek je u ulozi suosnivača Najka, legendarnog Fila Najta, Džejson Bejtman  je u ulozi Roba Strasera – njegovog direktora marketinga, dok je Vajola Dejvis u ulozi beskompromisne majke koja zna vrednost neizmernog talenta svog sina i košarkaškog fenomena koji će postati najveća sportska legenda svih vremena. U filmu pratimo Vakarovo nastojanje da stekne poverenje Džordanove porodice, trenera i najbližih saradnika s namerom da uveri tada veoma mladu NBA zvezdu u usponu da potpiše partnerski ugovor. Ugovor koji je Najku osigurao poziciju najvećeg brenda sportske odeće i obuće danas.",
                            Director = "Ben Affleck",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Air",
                            TrailerUrl = "https://www.youtube.com/watch?v=QIo12F3Uk0s&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovieId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectionTypeId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TheaterId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieId1");

                    b.HasIndex("ProjectionTypeId");

                    b.HasIndex("ProjectionTypeId1");

                    b.HasIndex("TheaterId");

                    b.HasIndex("TheaterId1");

                    b.ToTable("Projections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47c13a07-c890-4718-94f9-dbd82632a557"),
                            IsDeleted = false,
                            IsSold = false,
                            MovieId = new Guid("f68a0b29-91b2-4884-ba25-81f18a3b7ac6"),
                            Price = 500,
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2"),
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            Time = new DateTime(2023, 5, 16, 23, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106"),
                            Name = "2D"
                        },
                        new
                        {
                            Id = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2"),
                            Name = "3D"
                        },
                        new
                        {
                            Id = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6"),
                            Name = "4D"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33766ed9-6fd4-45d6-bbb1-1d6149de08fb"),
                            Number = 1,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("2e0f05a6-92c9-4c3f-973b-496aa5e92c08"),
                            Number = 2,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("f8944228-1f2b-4e7a-8b24-b34a95f8870e"),
                            Number = 3,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("2d711af2-6a1b-4a3c-a910-0893b69d1a7d"),
                            Number = 4,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("a1922f35-6f6e-431e-b3e4-60d8eb986ace"),
                            Number = 1,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("fd9d8e8e-5c3d-4c9c-af5a-3570a7c24dac"),
                            Number = 2,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("71dc739b-a8cb-48b2-9aa9-7351e3100527"),
                            Number = 3,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("12f85304-ec7b-438e-96b7-da000598e447"),
                            Number = 4,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("4f00d1cf-a073-4da2-a1bf-3e93beac7e02"),
                            Number = 5,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("319da221-bc0b-41ca-ab87-f8033a148a86"),
                            Number = 6,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("97ed9f79-f515-4751-9600-3c064dd7ea7a"),
                            Number = 7,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("afc061fa-e1d1-4779-900b-8945bafd3ab9"),
                            Number = 8,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("3f6da8cc-8dd1-491b-8b97-0b1f1b150ea4"),
                            Number = 9,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("fa3095c2-28af-401f-8ca5-ab11c4a0cf40"),
                            Number = 10,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("a78dd827-ef50-4530-b8f1-b3bfa703773d"),
                            Number = 1,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("e09178b8-4d9a-4108-8fb8-844e6b6d124a"),
                            Number = 2,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d48267b7-86dc-4415-ae01-06ab4f2e1ff5"),
                            Number = 3,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("719fe0c5-9978-4895-9355-cbe91bfe36b7"),
                            Number = 4,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d679b49f-77bc-47e5-b9ab-b71b525ea1de"),
                            Number = 5,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("89a324c2-d908-4694-9932-d403494bf2ff"),
                            Number = 6,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("bc04445b-5948-439a-8e55-5e60a7727e03"),
                            Number = 7,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8d990edc-928f-45b6-b29b-c49c89bcf79a"),
                            Number = 8,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("40bc9ab3-7c09-4bb4-8ecf-1b1eae56a76b"),
                            Number = 9,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("2f37abe3-cbf2-4908-94dd-4de7e20efef9"),
                            Number = 10,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("7938b48e-ffef-4ef6-b76a-6bfd5df9ea58"),
                            Number = 11,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("e9eb2f43-cd02-4996-8ab2-d0f2e63c4b6b"),
                            Number = 12,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("f5bc43c1-5e4e-4e4f-b69e-657ab284de23"),
                            Number = 13,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("2270f137-2a96-4fdb-9bb3-d87a7fab47d4"),
                            Number = 14,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("28a76c56-55db-4e2f-aed7-865ae379cba8"),
                            Number = 15,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("3963315b-2da5-47ee-9752-ab53ac2b932e"),
                            Number = 16,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("41ac559e-3e9f-457c-8c89-e0d9204b4a47"),
                            Number = 17,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("a1663235-ba9a-4d49-bbd4-4d7cf682d416"),
                            Number = 18,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("f97ef200-066c-4690-99e5-3270fcdec9c6"),
                            Number = 19,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("a0a3416e-ddd6-437c-ada4-3942542f10d0"),
                            Number = 20,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("c9e4be8d-a71d-46bb-898e-2b189c5d873e"),
                            Number = 1,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("22ce86ac-7398-476b-85bb-4eae57633e6d"),
                            Number = 2,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("ec33164f-0064-487c-afce-1b56c23147bb"),
                            Number = 3,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("f9b63149-342d-4ff9-95b5-4670759820a6"),
                            Number = 4,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("0dcf3daf-e0e2-49c1-b583-e4cc279e8596"),
                            Number = 5,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("36ea8ff7-0993-4e45-9a94-ced17fb56328"),
                            Number = 6,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("cc16ffdb-af08-4efc-b04b-4c2fe90834b2"),
                            Number = 7,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("c36afbee-7a7e-4f10-92af-a91ecd3d4a0a"),
                            Number = 8,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("44928ee1-950a-44d5-a43a-54d826978314"),
                            Number = 9,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("d755190d-f708-4f28-ba5c-2d3a787efd5c"),
                            Number = 10,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("2176a9b9-f586-4da7-a562-60c94fed655e"),
                            Number = 11,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("ed1ee50d-c158-4612-8017-184ed8b602e7"),
                            Number = 12,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("ac243e42-947c-4fb0-a47b-d7654b554493"),
                            Number = 13,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("f34c768f-6448-4aae-bd22-0bc3e94fac22"),
                            Number = 14,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("59d65494-d895-46f9-a09b-7c689416696a"),
                            Number = 15,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("13948e86-cca8-4fff-9fa2-090d77fb7a6e"),
                            Number = 1,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("cae275de-4a88-47d4-80e5-d825f1a58cb9"),
                            Number = 2,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("6ad07e2e-dec6-4bbb-b920-a980ad804f27"),
                            Number = 3,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("b1130c72-0a6a-4180-a551-f9803c7fe140"),
                            Number = 4,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("f4ce9898-0a0c-4d05-92f6-94c033743a56"),
                            Number = 5,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("b1dae04e-9307-4391-a722-e1f7b6a99b3d"),
                            Number = 6,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("c28713ba-84d3-4dd7-853e-9b1b762060d2"),
                            Number = 7,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("fd6e4c92-c742-4019-931b-e87a7d9c798d"),
                            Number = 8,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("856f7366-2035-4966-b6df-0812cc282c1d"),
                            Number = 9,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("64648f82-c40a-405d-b41c-beb895974f3d"),
                            Number = 10,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("89544b80-798a-4a5a-b113-24d5fc45f7da"),
                            Number = 11,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("da231c85-3a96-4303-9ebc-4e211f610ddc"),
                            Number = 12,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("f7ee3d67-3e5f-43b5-aeb1-b324a62269c2"),
                            Number = 13,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("61e0ee28-8e40-440c-9499-f0d573aeb9cc"),
                            Number = 14,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("5897d60e-d921-43b3-afb2-55e7be768b51"),
                            Number = 15,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("08c4d27c-d6c5-453c-adbb-08873ba36e94"),
                            Number = 1,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("441a13d0-3a71-49f2-ad66-2af37d4a258e"),
                            Number = 2,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("17593e9d-e2ce-4da1-abb9-4c6bb7adcead"),
                            Number = 3,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("04816eec-f46f-4214-bcec-46295e636ba6"),
                            Number = 4,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("6c6be953-f153-4e2c-ba3c-4410532e1214"),
                            Number = 5,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("9ca03123-8355-408c-afe8-9909fe01d618"),
                            Number = 6,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("d6ece622-4e32-4da9-adeb-907597c42456"),
                            Number = 7,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("1908d3d3-476b-4215-9b88-7b73c53bddb8"),
                            Number = 8,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("25131550-01c0-4bfc-8f74-01c5f5498da1"),
                            Number = 9,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("bdaf2662-f677-44cb-abf5-e5e3a37c821d"),
                            Number = 10,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            Name = "Sala 1"
                        },
                        new
                        {
                            Id = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            Name = "Sala 2"
                        },
                        new
                        {
                            Id = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            Name = "Sala 3"
                        },
                        new
                        {
                            Id = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            Name = "Sala 4"
                        },
                        new
                        {
                            Id = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            Name = "Sala 5"
                        },
                        new
                        {
                            Id = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            Name = "Sala 6"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("133e7b30-9350-4598-b6f4-0425822e5fcf"),
                            Created = new DateTime(2023, 4, 19, 17, 24, 40, 923, DateTimeKind.Local).AddTicks(6630),
                            Email = "david.fejes@gmail.com",
                            FirstName = "David",
                            LastName = "Fejes",
                            Password = "davidfejes",
                            Role = "LoggedUser",
                            Username = "davidfejes"
                        },
                        new
                        {
                            Id = new Guid("c666ed8e-5b05-432f-b7cd-fb0fe957d2bc"),
                            Created = new DateTime(2023, 4, 19, 17, 24, 40, 923, DateTimeKind.Local).AddTicks(6775),
                            Email = "stefan.bulaja@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Bulaja",
                            Password = "stefanbulaja",
                            Role = "LoggedUser",
                            Username = "stefanbulaja"
                        },
                        new
                        {
                            Id = new Guid("a4dd5ad4-9265-4f6a-b9c7-e42c6eb00ae8"),
                            Created = new DateTime(2023, 4, 19, 17, 24, 40, 923, DateTimeKind.Local).AddTicks(6806),
                            Email = "andija.tasic@gmail.com",
                            FirstName = "Andrija",
                            LastName = "Tasic",
                            Password = "andrijatasic",
                            Role = "LoggedUser",
                            Username = "andrijatasic"
                        });
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("TheaterId", "ProjectionTypeId");

                    b.HasIndex("ProjectionTypeId");

                    b.ToTable("TheaterProjectionType");

                    b.HasData(
                        new
                        {
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        },
                        new
                        {
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Movies.Movie", null)
                        .WithMany("Projections")
                        .HasForeignKey("MovieId1");

                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", "ProjectionType")
                        .WithMany()
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", null)
                        .WithMany("Projections")
                        .HasForeignKey("ProjectionTypeId1");

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", "Theater")
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany("Projections")
                        .HasForeignKey("TheaterId1");

                    b.Navigation("Movie");

                    b.Navigation("ProjectionType");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.Projection", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", null)
                        .WithMany()
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Navigation("Projections");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
