// <auto-generated />
using System;
using Cinema.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230427103341_updated-projection-bool-to-boolean")]
    partial class updatedprojectionbooltoboolean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("985c53a0-d42d-466d-84ee-f90bb5c2fa0e"),
                            Country = "USA",
                            Description = "Nakon katastrofalne nesreće na nepoznatoj planeti, pilot Mils (Adam Drajver) ubrzo otkriva da je zapravo bio nasukan na planetu Zemlju… pre 65 miliona godina.",
                            Director = "Scott Beck",
                            Distributor = "CON Film",
                            Duration = 93,
                            IsDeleted = false,
                            Name = "65",
                            TrailerUrl = "https://www.youtube.com/watch?v=bHXejJq5vr0&t=2s&ab_channel=SonyPicturesEntertainment",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("9c608aad-667e-4cdd-b5f3-65d753dd1dfc"),
                            Country = "USA",
                            Description = "Nakon što je dominirao bokserskim svetom, Adonis Krid je napredovao u karijeri i porodičnom životu. Kada je prijatelj iz detinjstva i bivši boksersko čudo.",
                            Director = "Michael B. Jordan",
                            Distributor = "Blitz Film Video doo",
                            Duration = 116,
                            IsDeleted = false,
                            Name = "Creed 3",
                            TrailerUrl = "https://www.youtube.com/watch?v=lvuR_Ny882g&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("22f59abd-89c1-424b-9427-d06a61dfba11"),
                            Country = "Serbia",
                            Description = "Priča je smeštena u četiri dana i prati Vuka, tridesetogodišnjeg povratnika iz zatvora koji, gonjen samoubistvom najboljeg druga, pokušava da spase njegovog mlađeg brata na veče godišnjice samoubistva.",
                            Director = "Luka Mihailović",
                            Distributor = "Art Vista",
                            Duration = 105,
                            IsDeleted = false,
                            Name = "Indigo Kristal",
                            TrailerUrl = "https://www.youtube.com/watch?v=8hULM38r66E&ab_channel=ArtVista",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("45891c23-d7e6-4056-999d-92163a771206"),
                            Country = "USA",
                            Description = "Mišel i Alen su u vezi. Odlučuju da pozovu svoje roditelje da se konačno sretnu kako bi se upoznali pre braka. Ispostavilo se da se roditelji već dobro poznaju, što dovodi do različitih mišljenja o braku.",
                            Director = "Michael Jacobs",
                            Distributor = "Blitz Film Video doo",
                            Duration = 95,
                            IsDeleted = false,
                            Name = "Maybe I Do",
                            TrailerUrl = "https://www.youtube.com/watch?v=MU9wJyel8VU&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("e755d64c-f8d5-4397-a194-a7acfd68e686"),
                            Country = "USA",
                            Description = "Nakon poslednjih ubistava koje je počinio Goustfejs, četvoro preživelih napuštaju Vudsboro i započinju novo poglavlje. U filmu VRISAK 6 Melisa Berera („Sem Karpenter“), Jasmin Savoj Braun („Mindi Miks-Martin“), Mejson Guding („Čed Miks-Martin), Džena Ortega („Tara Karpenter“), Hajden Panetir („Kirbi Rid“) i Kortni Koks („Gejl Veders“) vraćaju se svojim ulogama u ovoj franšizi, zajedno sa Džekom Čempionom, Henrijem Černijem, Lijanom Liberato, Dermotom Malronijem, Devinom Nekodom, Tonijem Revolorijem, Džošom Segarom i Samarom Viving.",
                            Director = "Matt Bettinelli-Olpin",
                            Distributor = "Taramount",
                            Duration = 123,
                            IsDeleted = false,
                            Name = "Scream 6",
                            TrailerUrl = "https://www.youtube.com/watch?v=h74AXqw4Opc&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("eb563027-2ee9-4335-85cd-f17f8428e6dc"),
                            Country = "USA",
                            Description = "Radnja novog filma odvija se širom sveta i donosi akciju posebne vrste. Džon Vik se suočava sa svojim najsmrtonosnijim protivnicima dosad u nadolazećem četvrtom nastavku serijala.",
                            Director = "Chad Stahelski",
                            Distributor = "Blitz Film Video doo",
                            Duration = 169,
                            IsDeleted = false,
                            Name = "John Wick: Chapter 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=80zGq9ABI7k&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("83cd9fbb-5fc1-4461-81bc-7cddd3d58e7d"),
                            Country = "USA",
                            Description = "Šarmantni lopov i grupa nesvakidašnjih avanturista upustili su se u epsku pljačku kako bi vratili izgubljenu relikviju. Međutim, kada se sukobe sa pogrešnim ljudima, stvari kreću po zlu.",
                            Director = "Jonathan Goldstein",
                            Distributor = "Taramount",
                            Duration = 134,
                            IsDeleted = false,
                            Name = "Dungeons & Dragons: Honor Among Thieves",
                            TrailerUrl = "https://www.youtube.com/watch?v=IiMinixSXII&t=11s&ab_channel=ParamountPictures",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("a5a67659-e299-4cc4-9f4e-77f4e96daa6d"),
                            Country = "USA",
                            Description = "Godina je 50. pne. Kineska carica je upravo zatvorena nakon državnog udara koji je podstaknuo Deng Tsin Kin, izdajnički princ. Uz pomoć Finaltesisa, feničanskog trgovca i njenog vernog telohranitelja Mai Vei, jedina ćerka carice, princeza Sas-Ji beži u Galiju da zatraži pomoć od dva hrabra ratnika Asteriksa i Obeliksa, koji su obdareni nadljudskom snagom zahvaljujući svom magičnom napitku. Naša dva nerazdvojna heroja rado prihvataju da pomognu princezi da spase svoju majku i oslobodi svoju zemlju. I tako počinje veliko putovanje i avantura na putu za Kinu. Ali Cezar i njegova moćna vojska, žedni novog osvajanja, takođe idu ka Srednjem kraljevstvu...",
                            Director = "Guillaume Canet",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Asterix & Obelix: L'Empire du Milieu",
                            TrailerUrl = "https://www.youtube.com/watch?v=E1-qmncJ5zw&ab_channel=BlitzFilmSrbija",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("9e1eb952-2c84-4cf1-a13d-20889aad8889"),
                            Country = "USA",
                            Description = "Zasnovan na komičnom i pokretačkom bestseleru Njujork Tajmsa, film Čovek zvani Oto govori o Otou Andersonu (Tom Henks), mrzovoljnom udovcu kome radost donosi jedino kritikovanje i osuđivanje svojih ogorčenih komšija.",
                            Director = "Marc Forster",
                            Distributor = "CON Film",
                            Duration = 126,
                            IsDeleted = false,
                            Name = "A Man Called Otto",
                            TrailerUrl = "https://www.youtube.com/watch?v=eFYUX9l-m5I&ab_channel=SonyPicturesEntertainment",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("da0b53bc-3179-47ff-914c-239b02d42658"),
                            Country = "USA",
                            Description = "Oskarovska ekipa filma, predvođena Ben Aflekom i Met Dejmonom, u filmu o jednom od najuticajnijih sportskih brendova svih vremena. Priča o legendarnoj patici koja je oduševila Džordana i \"spasila\" Najk! Film nas vraća u period osamdesetih godina, a Met Dejmon tumači lik Sonija Vakare, zaslužnog za potpisivanje ugovora s tada mladom košarkaškom zvezdom Majkl Džordanom. Ben Aflek je u ulozi suosnivača Najka, legendarnog Fila Najta, Džejson Bejtman  je u ulozi Roba Strasera – njegovog direktora marketinga, dok je Vajola Dejvis u ulozi beskompromisne majke koja zna vrednost neizmernog talenta svog sina i košarkaškog fenomena koji će postati najveća sportska legenda svih vremena. U filmu pratimo Vakarovo nastojanje da stekne poverenje Džordanove porodice, trenera i najbližih saradnika s namerom da uveri tada veoma mladu NBA zvezdu u usponu da potpiše partnerski ugovor. Ugovor koji je Najku osigurao poziciju najvećeg brenda sportske odeće i obuće danas.",
                            Director = "Ben Affleck",
                            Distributor = "Blitz Film Video doo",
                            Duration = 112,
                            IsDeleted = false,
                            Name = "Air",
                            TrailerUrl = "https://www.youtube.com/watch?v=QIo12F3Uk0s&ab_channel=BlitzFilmSrbija",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProjectionTypeId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106"),
                            Name = "2D"
                        },
                        new
                        {
                            Id = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2"),
                            Name = "3D"
                        },
                        new
                        {
                            Id = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6"),
                            Name = "4D"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a08c4dbd-75de-4fa3-ae7d-0520c441f3c1"),
                            Number = 1,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("f7dcc55e-cde8-4eb1-952b-0a9db021cd7c"),
                            Number = 2,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("b30841ff-69a3-4edb-b833-4bf4ee468665"),
                            Number = 3,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("c193a0ea-aa2f-4926-b1d7-0fc25fa9fe6b"),
                            Number = 4,
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3")
                        },
                        new
                        {
                            Id = new Guid("e0f40bf0-0504-4f7a-81f1-e3a035277bb9"),
                            Number = 1,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("3218aac6-7dad-4820-b4a0-7228d4615d63"),
                            Number = 2,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("881cfa46-98dc-416a-81cd-ea2c6da05f4c"),
                            Number = 3,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("116b7c45-e0fa-4f13-9ec5-ccec6a528b2c"),
                            Number = 4,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("b2ae66a5-aeae-4ab7-bfa3-ba3822baa3b6"),
                            Number = 5,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("5e1e11e6-5802-4073-ade9-605ffb97d47f"),
                            Number = 6,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("961b9daa-a615-4369-9331-203495b692d8"),
                            Number = 7,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("1a010e7a-2b65-4f41-b89d-073224f09a72"),
                            Number = 8,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("41a7d560-81ba-4e80-9171-50c5820747a6"),
                            Number = 9,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("8f1a8bd3-be1c-4d9e-8952-fab33adb427a"),
                            Number = 10,
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8")
                        },
                        new
                        {
                            Id = new Guid("44d30a02-be36-44eb-ade8-3a36e2cf6bb2"),
                            Number = 1,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d288108a-8e1d-41e9-ac57-775dc33b917a"),
                            Number = 2,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("ca777666-6ab2-4448-8d9c-09264ed60d74"),
                            Number = 3,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("11f52556-470f-4d8b-b1e4-e8b867aeed16"),
                            Number = 4,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("8503da19-d33d-4740-9623-4a3f10accbce"),
                            Number = 5,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("de55acf4-acde-4980-8498-8e1cbd436bda"),
                            Number = 6,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("897df960-f5da-435e-af1c-ff52fd7c73d7"),
                            Number = 7,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("7645f5d3-7527-487f-899f-3bfda3a12f43"),
                            Number = 8,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("17bcded1-6baf-46e1-8f5d-ade1e095c5eb"),
                            Number = 9,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("a38d94c9-bc52-4f14-b0eb-7df7228963e4"),
                            Number = 10,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("82ca7f8d-fe65-4890-a592-0afcc161155d"),
                            Number = 11,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("fa09a415-b5b0-4236-8ba2-44541d851d30"),
                            Number = 12,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("3bde2d76-061d-4940-99bb-1309a594643d"),
                            Number = 13,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("ab7b85a6-ba80-46b3-99c8-22e44df83fa9"),
                            Number = 14,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("1616d340-f33e-4045-b5b2-c6a15be805c7"),
                            Number = 15,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("44b5e053-54a1-440c-97aa-d59d4099abba"),
                            Number = 16,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("e402d292-9b9f-49d8-99b1-2de87e1bcdac"),
                            Number = 17,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("991f15f1-5a27-497b-9da8-55dbd1440b4f"),
                            Number = 18,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("84ae68b9-e725-4807-ac2b-6c65beed89df"),
                            Number = 19,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("a6af72c6-47be-4580-8c4c-d723e8a0f330"),
                            Number = 20,
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12")
                        },
                        new
                        {
                            Id = new Guid("d259e8e9-22b4-4c95-a6a2-84c829e3bbf3"),
                            Number = 1,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("e41a5e8d-44eb-41ef-b8e3-234e8dd46225"),
                            Number = 2,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("36d70ef0-4d42-4f1b-b137-c5b1c0516b32"),
                            Number = 3,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("8b0048fd-a1a2-4ac3-bd18-fb2015964108"),
                            Number = 4,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("da3db1a6-ad4f-4a1c-8eb9-f50163d51b36"),
                            Number = 5,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("d0178907-ae7d-4d42-9767-3399292986eb"),
                            Number = 6,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("cab7fad4-786f-4b87-8684-f7974d7968b3"),
                            Number = 7,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("f7984165-3990-4d4d-8b93-40b57d3bc3e5"),
                            Number = 8,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("99ec2d2a-3b5b-4358-b845-b16ecaba9463"),
                            Number = 9,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("98527eb8-9199-4264-81bc-e8c1a784f381"),
                            Number = 10,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("b5918646-9a3c-43c0-9441-c21772c8a4ec"),
                            Number = 11,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("7ac28034-9ed6-47bd-b3c1-1c1d6e3a2916"),
                            Number = 12,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("044f2d98-6ad3-4e42-b2ac-0bcf1102d03b"),
                            Number = 13,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("1dfa42b9-d679-439b-b2d5-afd0201e1016"),
                            Number = 14,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("0fa8eb89-b1ed-44b6-87c2-730edd70c84e"),
                            Number = 15,
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335")
                        },
                        new
                        {
                            Id = new Guid("25f9d4b5-6348-4c8d-a5bf-c6760bc85b98"),
                            Number = 1,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("8f371c79-1880-4c7a-bab2-14ecbea69b56"),
                            Number = 2,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("2a0e1638-650c-448b-9527-5d06686b0b50"),
                            Number = 3,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("e846f3a7-7a6f-496a-81b8-d9b60f0aea98"),
                            Number = 4,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("de70057c-84a8-450f-85ff-4164a50f2981"),
                            Number = 5,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("618cf44a-a24e-4bf5-b666-fffbe3890aec"),
                            Number = 6,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("6bd727de-617e-4be0-bdad-5256011228e0"),
                            Number = 7,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("b35a7f08-9ff4-4c2e-861a-00df93f10c6e"),
                            Number = 8,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("96a7012f-f957-42fc-afe9-7b010f2787cf"),
                            Number = 9,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("692e1666-121c-42f3-ba4e-65a2fc1e2faf"),
                            Number = 10,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("d4221531-ef7c-44a8-86e0-ab4035c90a3d"),
                            Number = 11,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("6abeebf6-b441-4df4-988a-baa90f2c09c7"),
                            Number = 12,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("f8dce239-39e8-4b9d-ac03-e2a9a95ee331"),
                            Number = 13,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("6cb4aa2b-a0b8-48b1-8a0b-66f9ae01a317"),
                            Number = 14,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("ebd56e5f-e98b-4acd-aef8-cfc980833388"),
                            Number = 15,
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb")
                        },
                        new
                        {
                            Id = new Guid("8b150c74-35a6-4989-8374-3751c836ffae"),
                            Number = 1,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("74800c51-cf2f-4931-bd68-0d1853edc868"),
                            Number = 2,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("652f4b18-040b-4efb-ba17-80bba6ef9376"),
                            Number = 3,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("4cf5acd1-b2d2-4da3-9229-46fa58f5098a"),
                            Number = 4,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("b8f51e0b-75f6-4683-9479-94157aa84122"),
                            Number = 5,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("52736e5a-7cd4-4f8c-9442-da29376d1e47"),
                            Number = 6,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("e9174d9b-2408-463b-a6d9-ff4a4bfe48e4"),
                            Number = 7,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("bb148795-8bfe-417b-ba1b-a1f59c5097e5"),
                            Number = 8,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("fb26d6bf-6b98-4dff-94f2-64fa4b69ac0a"),
                            Number = 9,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        },
                        new
                        {
                            Id = new Guid("72b2c504-ab13-494e-a433-5c62f53c3171"),
                            Number = 10,
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            Name = "Sala 1"
                        },
                        new
                        {
                            Id = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            Name = "Sala 2"
                        },
                        new
                        {
                            Id = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            Name = "Sala 3"
                        },
                        new
                        {
                            Id = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            Name = "Sala 4"
                        },
                        new
                        {
                            Id = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            Name = "Sala 5"
                        },
                        new
                        {
                            Id = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            Name = "Sala 6"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86e02402-201c-4523-b89b-678280868add"),
                            Created = new DateTime(2023, 4, 27, 12, 33, 41, 332, DateTimeKind.Local).AddTicks(4558),
                            Email = "david.fejes@gmail.com",
                            FirstName = "David",
                            LastName = "Fejes",
                            Password = "davidfejes",
                            Role = "LoggedUser",
                            Username = "davidfejes"
                        },
                        new
                        {
                            Id = new Guid("0c609c5c-730c-4581-808f-1dcf43ca98d1"),
                            Created = new DateTime(2023, 4, 27, 12, 33, 41, 332, DateTimeKind.Local).AddTicks(4688),
                            Email = "stefan.bulaja@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Bulaja",
                            Password = "stefanbulaja",
                            Role = "LoggedUser",
                            Username = "stefanbulaja"
                        },
                        new
                        {
                            Id = new Guid("d6cd8651-303e-49f9-b0ef-a86ea152e6b6"),
                            Created = new DateTime(2023, 4, 27, 12, 33, 41, 332, DateTimeKind.Local).AddTicks(4702),
                            Email = "andija.tasic@gmail.com",
                            FirstName = "Andrija",
                            LastName = "Tasic",
                            Password = "andrijatasic",
                            Role = "LoggedUser",
                            Username = "andrijatasic"
                        });
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.Property<Guid>("TheaterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectionTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("TheaterId", "ProjectionTypeId");

                    b.HasIndex("ProjectionTypeId");

                    b.ToTable("TheaterProjectionType");

                    b.HasData(
                        new
                        {
                            TheaterId = new Guid("f1cbab66-97ab-4cbe-a2ec-b4d84dde9bb3"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("52900eaf-4ba1-40a1-aaa9-c564e532afa8"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("e77354fc-8661-4a2c-80d1-d8e0557d4106")
                        },
                        new
                        {
                            TheaterId = new Guid("a322aedb-053b-4507-895e-150390686b12"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7f251baa-0f7f-4fb4-ba9b-e807553b1335"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("faaf87a8-81d2-44e0-9dce-a2e7f48d85d2")
                        },
                        new
                        {
                            TheaterId = new Guid("7c7029a8-dbf9-4fa0-ad1e-b67f65be85eb"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        },
                        new
                        {
                            TheaterId = new Guid("d77c00d9-8913-4bad-83f9-5d9a054c81d1"),
                            ProjectionTypeId = new Guid("dfb97424-2128-4cba-854e-5ef051d2e2e6")
                        });
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Movies.Movie", "Movie")
                        .WithMany("Projections")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", "ProjectionType")
                        .WithMany("Projections")
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", "Theater")
                        .WithMany("Projections")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("ProjectionType");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Seats.Seat", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Tickets.Ticket", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.Projection", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheaterProjectionType", b =>
                {
                    b.HasOne("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", null)
                        .WithMany()
                        .HasForeignKey("ProjectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.AggregateModels.Theaters.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Movies.Movie", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.Projection", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Projections.ProjectionTypes.ProjectionType", b =>
                {
                    b.Navigation("Projections");
                });

            modelBuilder.Entity("Cinema.Domain.AggregateModels.Theaters.Theater", b =>
                {
                    b.Navigation("Projections");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
